/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YouthEmpowermentGuideRouteImport } from './routes/youth-empowerment-guide'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRsvpRouteImport } from './routes/api/rsvp'
import { Route as ApiInquireRouteImport } from './routes/api/inquire'
import { Route as ApiEventsRouteImport } from './routes/api/events'

const YouthEmpowermentGuideRoute = YouthEmpowermentGuideRouteImport.update({
  id: '/youth-empowerment-guide',
  path: '/youth-empowerment-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRsvpRoute = ApiRsvpRouteImport.update({
  id: '/api/rsvp',
  path: '/api/rsvp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInquireRoute = ApiInquireRouteImport.update({
  id: '/api/inquire',
  path: '/api/inquire',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/youth-empowerment-guide': typeof YouthEmpowermentGuideRoute
  '/api/events': typeof ApiEventsRoute
  '/api/inquire': typeof ApiInquireRoute
  '/api/rsvp': typeof ApiRsvpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/youth-empowerment-guide': typeof YouthEmpowermentGuideRoute
  '/api/events': typeof ApiEventsRoute
  '/api/inquire': typeof ApiInquireRoute
  '/api/rsvp': typeof ApiRsvpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/youth-empowerment-guide': typeof YouthEmpowermentGuideRoute
  '/api/events': typeof ApiEventsRoute
  '/api/inquire': typeof ApiInquireRoute
  '/api/rsvp': typeof ApiRsvpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/youth-empowerment-guide'
    | '/api/events'
    | '/api/inquire'
    | '/api/rsvp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/youth-empowerment-guide'
    | '/api/events'
    | '/api/inquire'
    | '/api/rsvp'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/youth-empowerment-guide'
    | '/api/events'
    | '/api/inquire'
    | '/api/rsvp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  YouthEmpowermentGuideRoute: typeof YouthEmpowermentGuideRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiInquireRoute: typeof ApiInquireRoute
  ApiRsvpRoute: typeof ApiRsvpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/youth-empowerment-guide': {
      id: '/youth-empowerment-guide'
      path: '/youth-empowerment-guide'
      fullPath: '/youth-empowerment-guide'
      preLoaderRoute: typeof YouthEmpowermentGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rsvp': {
      id: '/api/rsvp'
      path: '/api/rsvp'
      fullPath: '/api/rsvp'
      preLoaderRoute: typeof ApiRsvpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inquire': {
      id: '/api/inquire'
      path: '/api/inquire'
      fullPath: '/api/inquire'
      preLoaderRoute: typeof ApiInquireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  YouthEmpowermentGuideRoute: YouthEmpowermentGuideRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiInquireRoute: ApiInquireRoute,
  ApiRsvpRoute: ApiRsvpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
