/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YouthEmpowermentGuideRouteImport } from './routes/youth-empowerment-guide'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as UsInitiativesRouteImport } from './routes/us-initiatives'
import { Route as TermsOfUseRouteImport } from './routes/terms-of-use'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as GhanaInitiativesRouteImport } from './routes/ghana-initiatives'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PressIndexRouteImport } from './routes/press.index'
import { Route as LeadershipIndexRouteImport } from './routes/leadership.index'
import { Route as PressSlugRouteImport } from './routes/press.$slug'

const YouthEmpowermentGuideRoute = YouthEmpowermentGuideRouteImport.update({
  id: '/youth-empowerment-guide',
  path: '/youth-empowerment-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const UsInitiativesRoute = UsInitiativesRouteImport.update({
  id: '/us-initiatives',
  path: '/us-initiatives',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfUseRoute = TermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const GhanaInitiativesRoute = GhanaInitiativesRouteImport.update({
  id: '/ghana-initiatives',
  path: '/ghana-initiatives',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PressIndexRoute = PressIndexRouteImport.update({
  id: '/press/',
  path: '/press/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipIndexRoute = LeadershipIndexRouteImport.update({
  id: '/leadership/',
  path: '/leadership/',
  getParentRoute: () => rootRouteImport,
} as any)
const PressSlugRoute = PressSlugRouteImport.update({
  id: '/press/$slug',
  path: '/press/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/ghana-initiatives': typeof GhanaInitiativesRoute
  '/impact': typeof ImpactRoute
  '/mission': typeof MissionRoute
  '/partners': typeof PartnersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/programs': typeof ProgramsRoute
  '/sponsors': typeof SponsorsRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/us-initiatives': typeof UsInitiativesRoute
  '/volunteer': typeof VolunteerRoute
  '/youth-empowerment-guide': typeof YouthEmpowermentGuideRoute
  '/press/$slug': typeof PressSlugRoute
  '/leadership/': typeof LeadershipIndexRoute
  '/press/': typeof PressIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/ghana-initiatives': typeof GhanaInitiativesRoute
  '/impact': typeof ImpactRoute
  '/mission': typeof MissionRoute
  '/partners': typeof PartnersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/programs': typeof ProgramsRoute
  '/sponsors': typeof SponsorsRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/us-initiatives': typeof UsInitiativesRoute
  '/volunteer': typeof VolunteerRoute
  '/youth-empowerment-guide': typeof YouthEmpowermentGuideRoute
  '/press/$slug': typeof PressSlugRoute
  '/leadership': typeof LeadershipIndexRoute
  '/press': typeof PressIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/ghana-initiatives': typeof GhanaInitiativesRoute
  '/impact': typeof ImpactRoute
  '/mission': typeof MissionRoute
  '/partners': typeof PartnersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/programs': typeof ProgramsRoute
  '/sponsors': typeof SponsorsRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/us-initiatives': typeof UsInitiativesRoute
  '/volunteer': typeof VolunteerRoute
  '/youth-empowerment-guide': typeof YouthEmpowermentGuideRoute
  '/press/$slug': typeof PressSlugRoute
  '/leadership/': typeof LeadershipIndexRoute
  '/press/': typeof PressIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/events'
    | '/ghana-initiatives'
    | '/impact'
    | '/mission'
    | '/partners'
    | '/privacy-policy'
    | '/programs'
    | '/sponsors'
    | '/terms-of-use'
    | '/us-initiatives'
    | '/volunteer'
    | '/youth-empowerment-guide'
    | '/press/$slug'
    | '/leadership/'
    | '/press/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/events'
    | '/ghana-initiatives'
    | '/impact'
    | '/mission'
    | '/partners'
    | '/privacy-policy'
    | '/programs'
    | '/sponsors'
    | '/terms-of-use'
    | '/us-initiatives'
    | '/volunteer'
    | '/youth-empowerment-guide'
    | '/press/$slug'
    | '/leadership'
    | '/press'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/events'
    | '/ghana-initiatives'
    | '/impact'
    | '/mission'
    | '/partners'
    | '/privacy-policy'
    | '/programs'
    | '/sponsors'
    | '/terms-of-use'
    | '/us-initiatives'
    | '/volunteer'
    | '/youth-empowerment-guide'
    | '/press/$slug'
    | '/leadership/'
    | '/press/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRoute
  GhanaInitiativesRoute: typeof GhanaInitiativesRoute
  ImpactRoute: typeof ImpactRoute
  MissionRoute: typeof MissionRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProgramsRoute: typeof ProgramsRoute
  SponsorsRoute: typeof SponsorsRoute
  TermsOfUseRoute: typeof TermsOfUseRoute
  UsInitiativesRoute: typeof UsInitiativesRoute
  VolunteerRoute: typeof VolunteerRoute
  YouthEmpowermentGuideRoute: typeof YouthEmpowermentGuideRoute
  PressSlugRoute: typeof PressSlugRoute
  LeadershipIndexRoute: typeof LeadershipIndexRoute
  PressIndexRoute: typeof PressIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/youth-empowerment-guide': {
      id: '/youth-empowerment-guide'
      path: '/youth-empowerment-guide'
      fullPath: '/youth-empowerment-guide'
      preLoaderRoute: typeof YouthEmpowermentGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/us-initiatives': {
      id: '/us-initiatives'
      path: '/us-initiatives'
      fullPath: '/us-initiatives'
      preLoaderRoute: typeof UsInitiativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-use': {
      id: '/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof TermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghana-initiatives': {
      id: '/ghana-initiatives'
      path: '/ghana-initiatives'
      fullPath: '/ghana-initiatives'
      preLoaderRoute: typeof GhanaInitiativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press/': {
      id: '/press/'
      path: '/press'
      fullPath: '/press/'
      preLoaderRoute: typeof PressIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership/': {
      id: '/leadership/'
      path: '/leadership'
      fullPath: '/leadership/'
      preLoaderRoute: typeof LeadershipIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press/$slug': {
      id: '/press/$slug'
      path: '/press/$slug'
      fullPath: '/press/$slug'
      preLoaderRoute: typeof PressSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRoute,
  GhanaInitiativesRoute: GhanaInitiativesRoute,
  ImpactRoute: ImpactRoute,
  MissionRoute: MissionRoute,
  PartnersRoute: PartnersRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProgramsRoute: ProgramsRoute,
  SponsorsRoute: SponsorsRoute,
  TermsOfUseRoute: TermsOfUseRoute,
  UsInitiativesRoute: UsInitiativesRoute,
  VolunteerRoute: VolunteerRoute,
  YouthEmpowermentGuideRoute: YouthEmpowermentGuideRoute,
  PressSlugRoute: PressSlugRoute,
  LeadershipIndexRoute: LeadershipIndexRoute,
  PressIndexRoute: PressIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
